### PR TITLE
Restart without reload.

### PR DESCRIPTION
**Pull request by 0xE282B0**
Maybe its easier to merge first to the jQuery free version. 
The path of the script is local at the moment. (script.src='./spritz.js?callback=cb';)

### CODE REVIEW

**Comment by elicwhite** [comment]
Awesome, the master branch should always be in working order though, so it would be good if you kept it pointing to the miserlou version, even though that seems silly in this case.

**Comment by 0xE282B0** [comment]
Okay? And how do I change that?

**Comment by elicwhite** [comment]
You changed it to point to the local script. Have it point to the actual version like it used to. :)

**Comment by 0xE282B0** [comment]
Ah, yes, of course. My thoughts were elsewhere.

**Pull request merged**
